### ISSUE TITLE
Constructing an AxisArray of an AxisArray

### ISSUE THREAD

**Issue by mdavezac** [JuliaArrays/AxisArrays.jl#103]
The array underlying the AxisArray of an AxisArray is an AxisArray:

~~~Julia
julia> a = AxisArray(zeros(2, 4), Axis{:a}((3, 4)))
2-dimensional AxisArray{Float64,2,...} with axes:
    :a, (3, 4)
    :col, Base.OneTo(4)
And data, a 2x4 Array{Float64,2}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

julia> b = AxisArray(a)
2-dimensional AxisArray{Float64,2,...} with axes:
    :row, Base.OneTo(2)
    :col, Base.OneTo(4)
And data, a 2-dimensional AxisArray{Float64,2,...} with axes:
    :a, (3, 4)
    :col, Base.OneTo(4)
And data, a 2x4 Array{Float64,2}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
~~~

Array, however, is a no-op:

~~~Julia
julia> a = Array{Int64}((1, 2))
1x2 Array{Int64,2}:
 4520822288  4520821504

julia> Array{Int64}(a) === a
true
~~~

I'm not sure what the default behaviour should be:

1. nesting as now (though, personally, I find it a bit surprising) 
1. no-op, disallow specifying axes
1. no-op unless new axes are specified, in which case a new wrapper over the original underlying array is supplied. It the number of supplied axis is < than the number of dimensions, use the existing axes, rather than `default_axes`. But that behaviour might all too special.

I'm happy to do a PR for 2 or 3

**Comment by timholy** [comment]
I kind of like 3. A more restricted version of that would throw an error unless you supplied the exact number of axes, but overall I think your "full" proposal is probably the most sensible.
