### ISSUE TITLE
Update to Julia v0.7

### ISSUE THREAD

**Issue by RalphAS** [JuliaArrays/AxisArrays.jl#141]
Here is package test output from 0.7-beta (omitting lots of deprecations):

| Test Summary:  |  Pass  |   Fail  |  Error  |  Total
| --- | --- | --- | --- | ---
| AxisArrays          |  140  |  12   |  14  |  166
|  Core              |       |  |        1   |   1
|  Intervals         |   60     |   |            60
|  Indexing          |   19     |  |     5   |  24
|  SortedVector      |    3  |   7  |      |    10
|  CategoricalVector  |    4  |   4   |   3  |   11
|  Search            |   26    |   |   |            26
|  Combine           |   28    |   |       4  |   32
|  README            |      |   |        1   |   1

Also, are users now expected to module-qualify all calls of `axes` (since `Base` exports an incompatible function)?

(Sorry to ping you, @mbauman, but this repo doesn't seem to get much attention and the last question is important for the image-processing ecosystem.)

**Comment by tlnagy** [comment]
Bump. Also @timholy?

**Comment by mbauman** [comment]
I'll try to get to this shortly! Sorry for letting it sit for so long. 

There are so many new goodies in 0.7 that AxisArrays will want to take advantage of, but that's much lower priority.

**Comment by mbauman** [comment]
Fixed by #143
