### ISSUE TITLE
significant performance regression versus 0.3.0

### ISSUE THREAD

**Issue by colinxs** [JuliaArrays/AxisArrays.jl#169]
```julia
x=rand(3,3)
a=AxisArray(x, [:x,:y,:z], [:foo1, :foo2, :foo3])
@btime $a[:x, :foo1]
```

v0.3.0:
```5.115 ns (0 allocations: 0 bytes)```
v0.3.1 and v0.3.2
```294.645 ns (3 allocations: 80 bytes)```

versioninfo:
```
Julia Version 1.1.1
Commit 55e36cc308 (2019-05-16 04:10 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

**Comment by c42f** [comment]
Darn, this is probably due to the trait refactoring I did in #163.

**Comment by c42f** [comment]
Does #170 fix this for your real use case?

**Comment by colinxs** [comment]
It looks like #170 fixes the above. Thanks for the quick fix!

Unfortunately I'm still running into a few performance issues when slicing. I think these aren't new, however (tested with v0.3.0 as well as #170)

```julia
x=rand(3,3)
y=rand(3)
a=AxisArray(x, [:x,:y,:z], [:foo1, :foo2, :foo3])
au=AxisArray(uview(x), [:x,:y,:z], [:foo1, :foo2, :foo3])
# With AxisArrays
@btime $y .= view($a, :x, :)
  # 500.005 ns (3 allocations: 96 bytes)
@btime $y .= view($au, :x, :)
  # 357.435 ns (2 allocations: 96 bytes)
@btime $y .= view($au, 1, :)
  # 358.857 ns (2 allocations: 96 bytes)
@btime $y .= $au[:, 1]
  # 275.429 ns (3 allocations: 160 bytes)

# Without AxisArrays
@btime $y .= view($x, 1, :)
  # 15.149 ns (1 allocation: 48 bytes)
 @btime $y .= uview($x, 1, :)
  # 14.594 ns (0 allocations: 0 bytes)
@btime $y .= $x[:, 1]
  # 29.032 ns (1 allocation: 112 bytes)
```

So it appears that any kind of slicing, with or without `view` and integer indexing, is quite a bit slower.

**Comment by c42f** [comment]
Symbol-based indexing will always have a performance hit of some kind.

I'm not so sure whether the integer slicing performance hit relative to normal arrays is expected — feel free to open a separate issue for that if you like.

**Comment by timholy** [comment]
What's `uview`?

**Comment by colinxs** [comment]
They are stack-allocated array views from UnsafeArrays.jl. They are quite
useful for getting maximally performant code.

Colin X Summers
University of Washington
Personal Robotics Lab
www.colinxsummers.com

**Comment by c42f** [comment]
I bumped the project version to 0.3.3 so we can have this bug fixed.

@JuliaRegistrator register
