### ISSUE TITLE
Register and tag?

### ISSUE THREAD

**Issue by timholy** [JuliaArrays/AxisArrays.jl#37]
I'd love to make use of this package in the upcoming Images rewrite, and for that to work nicely we'll need to register & tag it. Is there a list of things that need to be addressed before that happens? It will be some time (week or two?) before the need is urgent, so there's time to address issues. I'm happy to do the work myself.

Also, if @mbauman would like to ditch implicit responsibility for the package, perhaps we should consider moving this to [JuliaArrays](https://github.com/JuliaArrays). I just moved a bunch of my packages there.

**Comment by mbauman** [comment]
That sounds great, on both accounts.  I've been really excited to see this prototype start to make it into real uses.  I'm happy to continue helping maintain as I'm able, but I think moving to a more collaborative organization is a great idea.

I'll try to find some time to review my notes from long ago and see what I think is crucial for making this a fully supported, registered package.

**Comment by timholy** [comment]
Given that there have been a few updates (including one "roadmap" item being checked off), how are we doing now?

Test coverage is 89%, which seems pretty good. Still, if you're concerned about seeing this go into the wild that's one thing I could help improve.

**Comment by ajkeller34** [comment]
I'd also be eager to use this package if it were registered!

**Comment by mbauman** [comment]
Let's do it. One last thing: I'd like to make sure that any examples on the README work.  It looks like there's still some `unsafe_` range issues right now, but I don't have time to dig into it further.

**Comment by timholy** [comment]
I can probably get to this in the next couple of days (unless someone else beats me to it).

Excited to see this done; registering & tagging this is not yet the bottleneck in https://github.com/timholy/Images.jl/issues/542 (I still have a fair bit of other stuff to do), but it's not far off, either.

**Comment by timholy** [comment]
Closed by https://github.com/JuliaLang/METADATA.jl/pull/6666

**Comment by mbauman** [comment]
Great work, Tim! Thanks so much for joining forces here and doing the bulk of this work.  🎉

**Comment by timholy** [comment]
Well, I'm not sure that's true; I may have started this package oh-so-long ago, but you did all the care from it's preschool days through high school. I was there to help at around the time of graduation :smile:.

**Comment by timholy** [comment]
But yes, definitely cause for celebration! :fireworks:
