### ISSUE TITLE
Should indexing return copies?

### ISSUE THREAD

**Issue by mbauman** [JuliaArrays/AxisArrays.jl#38]
When I started development of this package, it was somewhat of a testbed for new indexing behaviors.  I tried to make the package rather opinionated on how I believed indexing should work.  One of those opinions was that indexing should return views by default.

Base Julia has caught up (and surpassed) AxisArrays in terms of APL indexing, but it hasn't caught the view train yet.  Should AxisArrays take a step back and match behaviors?

**Comment by timholy** [comment]
Yes, I've had the same thought. Let's do that.
