### ISSUE TITLE
Indexing by Reals

### ISSUE THREAD

**Issue by ajkeller34** [JuliaArrays/AxisArrays.jl#50]
I've been incorporating AxisArrays into my measurement code and I have got to say, it is really awesome. Great work. One small thing that tripped me up a bit was the following:

```
julia> A = AxisArray(rand(10,10), Axis{:test1}(0.1:0.1:1.0), Axis{:test2}(0.1:0.1:1.0))
2-dimensional AxisArray{Float64,2,...} with axes:
    :test1, 0.1:0.1:1.0
    :test2, 0.1:0.1:1.0
And data, a 10×10 Array{Float64,2}:
 0.956542   0.269435   0.968573  0.749255  0.931304   0.0717015  0.881473   0.396549  0.23055    0.0553351
 0.645476   0.745046   0.127696  0.939494  0.624804   0.209243   0.390447   0.335097  0.0910745  0.258535 
 0.0884433  0.342941   0.163901  0.521877  0.876765   0.0489701  0.796682   0.365296  0.254204   0.568327 
 0.205803   0.540466   0.891773  0.704059  0.109656   0.91213    0.0746333  0.802257  0.220095   0.332555 
 0.0624195  0.0513494  0.863017  0.920406  0.443187   0.566314   0.57402    0.601021  0.0832811  0.355787 
 0.615837   0.780253   0.697182  0.587102  0.571548   0.698586   0.249986   0.714737  0.253774   0.876721 
 0.50435    0.790261   0.464834  0.90049   0.0769789  0.395214   0.262674   0.485041  0.645104   0.470171 
 0.976307   0.477756   0.576011  0.975836  0.664999   0.54624    0.28258    0.970559  0.654953   0.589304 
 0.102939   0.790315   0.141168  0.208602  0.990242   0.752532   0.0452516  0.687015  0.740944   0.4406   
 0.700986   0.795746   0.645764  0.979793  0.287919   0.398423   0.0822585  0.895504  0.446748   0.534195 

julia> A[Axis{:test2}(0.1)]
ERROR: BoundsError: attempt to access 10×10 Array{Float64,2} at index [Colon(),0.1]
 in throw_boundserror(::Array{Float64,2}, ::Tuple{Colon,Float64}) at ./abstractarray.jl:355
 in checkbounds at ./abstractarray.jl:284 [inlined]
 in _getindex at ./multidimensional.jl:270 [inlined]
 in getindex at ./abstractarray.jl:752 [inlined]
 in getindex at /Users/ajkeller/.julia/v0.5/AxisArrays/src/indexing.jl:52 [inlined]
 in getindex(::AxisArrays.AxisArray{Float64,2,Array{Float64,2},Tuple{AxisArrays.Axis{:test1,FloatRange{Float64}},AxisArrays.Axis{:test2,FloatRange{Float64}}}}, ::AxisArrays.Axis{:test2,Float64}) at /Users/ajkeller/.julia/v0.5/AxisArrays/src/indexing.jl:76
```

I soon realized of course that dimensional axes are not allowed to be indexed by `Real` elements, but it seems like the [intended error message](https://github.com/JuliaArrays/AxisArrays.jl/blob/a63fd44fb7e4dd5c6036a4d8a8892f5c515739df/src/indexing.jl#L127) is not being delivered.

In my use case it would be really great to be able to index by a real value. (Let's say you're measuring a 2D sweep, where your axis values are probably coming from ranges with nonzero step size, and you want to take a slice at a particular value on that axis to make a plot.) Just a suggestion, but something like the following seems to work:

```
julia> immutable Value{T}
         val::T
       end

julia> atvalue(x) = Value(x)
atvalue (generic function with 1 method)

julia> AxisArrays.axisindexes(::Type{AxisArrays.Dimensional}, ax::AbstractVector, idx::Value) = findfirst(ax.==idx.val)

julia> A[Axis{:test1}(atvalue(0.2)), Axis{:test2}(atvalue(0.3))]
0.12769615238125231
```

As an aside, it seems like indexing-by-value just works out of the box with Unitful numbers, because `Unitful.Quantity` is not a subtype of `Real`. It'd be nice if there were an option to make indexing by value work with `Real` numbers though.

**Comment by timholy** [comment]
There was some thought given to having floats index by value and ints by index, but that seems way too confusing. With an explicit wrapper type, that could work.

**Comment by mbauman** [comment]
Yes, exactly.  See https://github.com/JuliaArrays/AxisArrays.jl/issues/15#issuecomment-248461126 for more details.  `atvalue` index wrappers actually seem like a good solution to me.  The other alternative is to simply use a point interval (`A[0.2 .. 0.2, 0.3 .. 0.3]`), but that'll keep dimensions akin to `A[2:2, 3:3]`.

**Comment by ajkeller34** [comment]
Thanks for the details. We are definitely on the same page, I wouldn't want separate indexing behavior for floats and ints, especially given that axes can take on int values. I did try using intervals but wanted the dimension dropped for what I was doing, so I hope this feature can make it into the package at some point. Indexing by value is one of the few things I have been missing from my time with IGOR Pro (don't get me started on their scripting language), but AxisArrays gets me most of the way there and excels in many other regards.

I can prepare a PR or if you want to think on it, that's totally sensible, I'll just continue defining `atvalue` for my own uses in the mean time.

**Comment by timholy** [comment]
I'd be excited for a PR.
